"""added_new_columns

Revision ID: 408dd8de764a
Revises: 86e87882e89d
Create Date: 2025-11-12 03:16:23.851668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408dd8de764a'
down_revision: Union[str, None] = '86e87882e89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('kast_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'kast_name')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
