"""fix password hash

Revision ID: 86e87882e89d
Revises: 039bd04a9a2c
Create Date: 2025-10-21 02:58:17.556113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e87882e89d'
down_revision: Union[str, None] = '039bd04a9a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
        type_=sa.String(),
        existing_type=sa.String(15),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
        type_=sa.String(15),
        existing_type=sa.String(),
        existing_nullable=False
    )
    # ### end Alembic commands ###
