"""added_new_tables

Revision ID: 9eb8d5fd5375
Revises: caeb769c610a
Create Date: 2025-11-18 19:25:19.782440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb8d5fd5375'
down_revision: Union[str, None] = 'caeb769c610a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backlogs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=False),
    sa.Column('backlog_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('backlog_id', sa.Uuid(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['backlog_id'], ['backlogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('earnings', sa.Float(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('projects_ids', sa.ARRAY(sa.UUID()), nullable=False, server_default="{}"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'projects_ids')
    op.drop_column('users', 'earnings')
    op.drop_table('tasks')
    op.drop_table('backlogs')
    op.drop_table('projects')
    # ### end Alembic commands ###
